name: test

on:
  push:
    branches-ignore:
      - main

jobs:
  format-tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout code"
        uses: actions/checkout@v2
      - name: "setup go version"
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.7"
      - name: "assert go version"
        run: make test-go-version
      - name: "fetch 3rd party dependencies"
        run: make test-fetch-deps
      - name: "run code format"
        run: make test-format
      - name: "run code lint"
        run: make test-lint
      - name: "run code security"
        run: make test-security

  unit-tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout code"
        uses: actions/checkout@v2
      - name: "setup go version"
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.7"
      - name: "assert go version"
        run: make test-go-version
      - name: "run unit tests"
        run: make test-unit
